version: '3'

services:

  lift-tracker:
      container_name: "lift-tracker-revamped"
      build:
          context: ./
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
          - 8020:80
      restart: unless-stopped
